import React, { useState } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Lock, Building, Mail, User, ShieldCheck, ArrowLeft, ArrowRight, CheckCircle2, Sparkles } from 'lucide-react';

export default function LoginPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { login, registerCompany } = useAuth();
  const redirectPath = searchParams.get('redirect') || '/customs';
  const initialMode = searchParams.get('mode') === 'register' ? 'register' : 'login';
  const [mode, setMode] = useState(initialMode);
  const [formData, setFormData] = useState({ company: '', tin: '', contactName: '', email: '', phone: '', password: '', ppraCode: 'Customs Clearing Agent' });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [authError, setAuthError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    setAuthError('');
    try {
      if (mode === 'login') await login(formData.email, formData.password);
      else await registerCompany(formData);
      navigate(redirectPath);
    } catch (err) {
      console.error('Auth error:', err);
      if (err.code === 'auth/invalid-credential' || err.code === 'auth/wrong-password' || err.code === 'auth/user-not-found') setAuthError('Invalid corporate email or password. Please verify your credentials.');
      else if (err.code === 'auth/email-already-in-use') setAuthError("This email address is already registered. Please switch to 'Sign In'.");
      else if (err.code === 'auth/weak-password') setAuthError('Password must be at least 6 characters long.');
      else setAuthError(err.message || 'Authentication failed. Please verify your connection.');
    } finally { setIsSubmitting(false); }
  };

  const redirectNotice = redirectPath.includes('customs') ? { title: 'BURS Customs Engine access', text: 'Sign in or register your Botswana clearing firm to process invoices and organize your SAD 500 audit trail.' } : redirectPath.includes('tenders') ? { title: 'Friday Tender Radar access', text: 'Sign in or register to track, filter, and bookmark tenders matching your company's PPRA codes.' } : null;
  const update = (key, value) => setFormData({ ...formData, [key]: value });

  return (
    <div className="mx-auto grid min-h-[calc(100vh-9rem)] max-w-5xl items-center gap-10 py-10 lg:grid-cols-[0.9fr_1.1fr] lg:py-16">
      <div className="hidden lg:block"><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold text-slate-500 transition hover:text-slate-950"><ArrowLeft className="h-3.5 w-3.5" />Back to public overview</Link><div className="mt-12 max-w-md"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-sky-300 shadow-lg"><Sparkles className="h-5 w-5" /></div><p className="mt-8 text-xs font-black uppercase tracking-[0.2em] text-sky-600">Your operational home base</p><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950">Keep every important trade decision in reach.</h1><p className="mt-5 text-sm leading-7 text-slate-600">Your company account keeps customs history, tender opportunities, and the next action organized in one secure workspace.</p><div className="mt-8 space-y-4 text-sm font-semibold text-slate-700"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" /><span>Return to your work without starting over.</span></div><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" /><span>Keep your company context attached to every workflow.</span></div><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" /><span>Use the right tool for customs or tenders today.</span></div></div></div></div>
      <div className="w-full max-w-xl justify-self-center rounded-[2rem] border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-900/10 sm:p-8"><Link to="/" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-slate-500 transition hover:text-slate-950 lg:hidden"><ArrowLeft className="h-3.5 w-3.5" />Back to public overview</Link>{redirectNotice && <div className="mb-6 flex items-start gap-3 rounded-2xl border border-sky-200 bg-sky-50 p-4 text-xs text-sky-950"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-sky-600" /><div><strong className="block font-black text-sky-900">{redirectNotice.title}</strong><span className="mt-1 block leading-5 text-slate-600">{redirectNotice.text}</span></div></div>}<div className="flex items-start justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-sky-600">Kalahari.ai workspace</p><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">{mode === 'login' ? 'Welcome back.' : 'Set up your company.'}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{mode === 'login' ? 'Sign in to continue where your team left off.' : 'A few details are all you need to get started.'}</p></div><div className="hidden h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-sky-300 sm:flex"><Lock className="h-5 w-5" /></div></div>
        <div className="mt-7 grid grid-cols-2 rounded-2xl bg-slate-100 p-1 text-xs font-black text-slate-600"><button type="button" onClick={() => setMode('login')} className={mode === 'login' ? 'rounded-xl bg-white py-2.5 text-slate-950 shadow-sm' : 'rounded-xl py-2.5 transition hover:text-slate-950'}>Sign in</button><button type="button" onClick={() => setMode('register')} className={mode === 'register' ? 'rounded-xl bg-white py-2.5 text-slate-950 shadow-sm' : 'rounded-xl py-2.5 transition hover:text-slate-950'}>Register company</button></div>
        <form onSubmit={handleSubmit} className="mt-7 space-y-4">{mode === 'register' && <><div><label className="mb-1.5 block text-xs font-bold text-slate-700">Company / broker name</label><div className="relative"><Building className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input type="text" required value={formData.company} onChange={(e) => update('company', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10" placeholder="e.g. Kalahari Express Logistics" /></div></div><div><label className="mb-1.5 block text-xs font-bold text-slate-700">BURS tax identification (TIN)</label><input type="text" value={formData.tin} onChange={(e) => update('tin', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 font-mono text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10" placeholder="e.g. C0981248101" /></div><div><label className="mb-1.5 block text-xs font-bold text-slate-700">Authorized representative</label><div className="relative"><User className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input type="text" required value={formData.contactName} onChange={(e) => update('contactName', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10" placeholder="e.g. Lesego Moeti" /></div></div><div><label className="mb-1.5 block text-xs font-bold text-slate-700">Operating domain / PPRA code</label><select value={formData.ppraCode} onChange={(e) => update('ppraCode', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10"><option value="Customs Clearing Agent">Customs Clearing Agent / Freight Broker</option><option value="Code 03">Code 03: Civil Engineering &amp; Road Works</option><option value="Code 120">Code 120: ICT Technical Support &amp; Systems</option><option value="Code 10">Code 10: Borehole Drilling &amp; Water Engineering</option><option value="Code 02">Code 02: Electrical Works &amp; Substations</option><option value="Code 211">Code 211: Medical Equipment &amp; Supplies</option></select></div></>}
          <div><label className="mb-1.5 block text-xs font-bold text-slate-700">Corporate email address</label><div className="relative"><Mail className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input type="email" required value={formData.email} onChange={(e) => update('email', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10" placeholder="name@company.co.bw" /></div></div><div><label className="mb-1.5 block text-xs font-bold text-slate-700">Password</label><div className="relative"><Lock className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input type="password" required value={formData.password} onChange={(e) => update('password', e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-sm outline-none transition focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-500/10" placeholder="••••••••••••" /></div></div>
          {authError && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold leading-5 text-red-700">{authError}</div>}<button type="submit" disabled={isSubmitting} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 py-3.5 text-sm font-black text-white shadow-lg shadow-slate-950/10 transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"><span>{isSubmitting ? (mode === 'login' ? 'Signing you in…' : 'Creating your workspace…') : (mode === 'login' ? 'Sign in to workspace' : 'Create company workspace')}</span><ArrowRight className="h-4 w-4 text-sky-300" /></button></form><div className="mt-7 flex items-center justify-center gap-2 border-t border-slate-100 pt-5 text-[11px] font-semibold text-slate-400"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600" />Protected company workspace access</div>
      </div>
    </div>
  );
}
