import React, { useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Cpu, FileSpreadsheet, Radar, History, LogOut, Menu, X, MessageSquare, UserRound, ShieldAlert, Lock, Phone, CircleCheck } from 'lucide-react';

export default function Navbar({ starredCount = 0, historyCount = 0, pendingTicketsCount = 0 }) {
  const { currentUser, isAuthenticated, isAdmin, logout } = useAuth();
  const navigate = useNavigate();
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const handleLogout = () => {
    logout();
    setIsMenuOpen(false);
    navigate('/');
  };

  const closeMenu = () => setIsMenuOpen(false);
  const navLinkClass = ({ isActive }) => 'flex items-center gap-2 rounded-xl px-3.5 py-2.5 text-xs font-bold transition ' + (isActive ? 'bg-slate-950 text-white shadow-lg shadow-slate-900/10' : 'text-slate-600 hover:bg-white hover:text-slate-950');
  const mobileNavLinkClass = ({ isActive }) => 'flex items-center justify-between rounded-xl px-3.5 py-3 text-sm font-bold transition ' + (isActive ? 'bg-slate-950 text-white' : 'text-slate-700 hover:bg-slate-100');

  return (
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 shadow-sm backdrop-blur-xl">
      <div className="border-b border-slate-800 bg-slate-950 px-4 py-2 text-[11px] text-slate-300"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><span className="inline-flex items-center gap-2 font-semibold"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />Kalahari.ai operations online</span><div className="hidden items-center gap-4 sm:flex"><span className="inline-flex items-center gap-1.5 text-slate-400"><CircleCheck className="h-3 w-3 text-emerald-400" />Botswana-first workflows</span><a href="tel:+26772161038" className="inline-flex items-center gap-1.5 transition hover:text-white"><Phone className="h-3 w-3 text-sky-400" />+267 72161038</a></div></div></div>
      <div className="mx-auto flex h-[4.75rem] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <Link to="/" className="flex shrink-0 items-center gap-3" onClick={closeMenu}><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-950 text-sky-300 shadow-lg shadow-slate-950/15"><Cpu className="h-5 w-5" /></div><div><span className="block text-lg font-black tracking-tight text-slate-950">KALAHARI<span className="text-sky-600">.AI</span></span><span className="hidden text-[9px] font-bold uppercase tracking-[0.18em] text-slate-400 sm:block">Trade operations, organized</span></div></Link>
        <nav className="hidden items-center gap-1 rounded-2xl border border-slate-200 bg-slate-100/80 p-1.5 md:flex"><NavLink to="/" className={navLinkClass} end>Overview</NavLink><NavLink to="/customs" className={navLinkClass}><FileSpreadsheet className="h-4 w-4 text-sky-600" /><span>Customs</span>{!isAuthenticated && <Lock className="h-3 w-3 opacity-50" />}</NavLink><NavLink to="/tenders" className={navLinkClass}><Radar className="h-4 w-4 text-sky-600" /><span>Tenders</span>{!isAuthenticated && <Lock className="h-3 w-3 opacity-50" />}</NavLink><NavLink to="/workspace" className={navLinkClass}><History className="h-4 w-4 text-sky-600" /><span>Workspace</span>{!isAuthenticated ? <Lock className="h-3 w-3 opacity-50" /> : (starredCount > 0 || historyCount > 0) && <span className="h-2 w-2 rounded-full bg-emerald-500" />}</NavLink>{isAdmin && <NavLink to="/admin" className={navLinkClass}><ShieldAlert className="h-4 w-4 text-amber-500" /><span>Admin</span>{pendingTicketsCount > 0 && <span className="h-2 w-2 rounded-full bg-red-500" />}</NavLink>}</nav>
        <div className="hidden items-center gap-2 md:flex"><a href="https://wa.me/26772161038" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3.5 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-emerald-700"><MessageSquare className="h-3.5 w-3.5" />WhatsApp</a>{isAuthenticated ? <><Link to="/workspace" className="inline-flex max-w-[150px] items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-800 transition hover:bg-slate-50"><UserRound className="h-3.5 w-3.5 text-sky-600" /><span className="truncate">{currentUser?.company || 'Workspace'}</span></Link><button onClick={handleLogout} className="rounded-xl border border-slate-200 p-2.5 text-slate-400 transition hover:bg-red-50 hover:text-red-600" title="Sign Out"><LogOut className="h-3.5 w-3.5" /></button></> : <><Link to="/login" className="rounded-xl px-3 py-2.5 text-xs font-bold text-slate-700 transition hover:bg-slate-100">Sign in</Link><Link to="/login?mode=register" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3.5 py-2.5 text-xs font-bold text-white shadow-sm transition hover:bg-slate-800"><UserRound className="h-3.5 w-3.5 text-sky-300" />Create account</Link></>}</div>
        <button className="rounded-xl border border-slate-200 p-2.5 text-slate-700 md:hidden" onClick={() => setIsMenuOpen(!isMenuOpen)} aria-label={isMenuOpen ? 'Close navigation' : 'Open navigation'}>{isMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button>
      </div>
      {isMenuOpen && <div className="border-t border-slate-200 bg-white px-4 py-4 shadow-xl md:hidden"><nav className="grid gap-1"><NavLink to="/" className={mobileNavLinkClass} end onClick={closeMenu}>Overview</NavLink><NavLink to="/customs" className={mobileNavLinkClass} onClick={closeMenu}>Customs {!isAuthenticated && <Lock className="h-3.5 w-3.5 opacity-50" />}</NavLink><NavLink to="/tenders" className={mobileNavLinkClass} onClick={closeMenu}>Tenders {!isAuthenticated && <Lock className="h-3.5 w-3.5 opacity-50" />}</NavLink><NavLink to="/workspace" className={mobileNavLinkClass} onClick={closeMenu}>Workspace {!isAuthenticated && <Lock className="h-3.5 w-3.5 opacity-50" />}</NavLink>{isAdmin && <NavLink to="/admin" className={mobileNavLinkClass} onClick={closeMenu}>Admin <ShieldAlert className="h-3.5 w-3.5 text-amber-500" /></NavLink>}</nav><div className="mt-3 grid grid-cols-2 gap-2 border-t border-slate-100 pt-3">{isAuthenticated ? <button onClick={handleLogout} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-3 py-3 text-xs font-bold text-white"><LogOut className="h-3.5 w-3.5" />Sign out</button> : <><Link to="/login" onClick={closeMenu} className="rounded-xl border border-slate-200 px-3 py-3 text-center text-xs font-bold text-slate-700">Sign in</Link><Link to="/login?mode=register" onClick={closeMenu} className="rounded-xl bg-slate-950 px-3 py-3 text-center text-xs font-bold text-white">Create account</Link></>}<a href="https://wa.me/26772161038" target="_blank" rel="noopener noreferrer" className="col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-3 py-3 text-xs font-bold text-white"><MessageSquare className="h-3.5 w-3.5" />Talk to the team on WhatsApp</a></div></div>}
    </header>
  );
}
